"""Migration template generation system."""

import re
from datetime import datetime
from pathlib import Path


class MigrationTemplate:
    """Template for generating new migration files."""

    @staticmethod
    def validate_name(name: str) -> bool:
        """
        Validate migration name follows conventions.

        Args:
            name: Migration name (e.g., "add_new_field")

        Returns:
            True if valid, False otherwise
        """
        # Name should only contain lowercase letters, numbers, and underscores
        pattern = r'^[a-z][a-z0-9_]*$'
        return bool(re.match(pattern, name))

    @staticmethod
    def get_next_version(migrations_dir: Path) -> str:
        """
        Get the next migration version number.

        Args:
            migrations_dir: Directory containing migration files

        Returns:
            Next version number as string (e.g., "007")
        """
        if not migrations_dir.exists():
            return "001"

        # Find all migration files
        migration_files = list(migrations_dir.glob("*.py"))
        if not migration_files:
            return "001"

        # Extract version numbers
        versions = []
        for file in migration_files:
            match = re.match(r'^(\d+)_', file.stem)
            if match:
                versions.append(int(match.group(1)))

        if not versions:
            return "001"

        next_version = max(versions) + 1
        return f"{next_version:03d}"

    @staticmethod
    def generate_filename(version: str, name: str) -> str:
        """
        Generate migration filename.

        Args:
            version: Version number (e.g., "007")
            name: Migration name (e.g., "add_new_field")

        Returns:
            Filename (e.g., "007_add_new_field.py")
        """
        return f"{version}_{name}.py"

    @staticmethod
    def generate_class_name(version: str, name: str) -> str:
        """
        Generate migration class name.

        Args:
            version: Version number (e.g., "007")
            name: Migration name (e.g., "add_new_field")

        Returns:
            Class name (e.g., "Migration007AddNewField")
        """
        # Convert snake_case to CamelCase
        words = name.split('_')
        camel_name = ''.join(word.capitalize() for word in words)
        return f"Migration{version}{camel_name}"

    @staticmethod
    def generate_content(version: str, name: str, description: str = "") -> str:
        """
        Generate migration file content.

        Args:
            version: Version number (e.g., "007")
            name: Migration name (e.g., "add_new_field")
            description: Optional description

        Returns:
            Migration file content
        """
        class_name = MigrationTemplate.generate_class_name(version, name)
        version_name = f"{version}_{name}"

        if not description:
            description = f"Add description for {name}"

        current_date = datetime.now().strftime("%Y-%m-%d")

        return f'''"""Migration: {version_name}

{description}

Generated by: iccc migrate create
Date: {current_date}
"""

from iccc.db.migrations import Migration
from iccc.db.repositories import MongoDBClient


class {class_name}(Migration):
    """
    Migration: {version} - {name.replace('_', ' ')}

    Description:
        {description}

    Instructions:
        1. Implement the up() method to apply schema changes
        2. Implement the down() method to rollback changes
        3. Test your migration before committing
        4. Add this migration to get_all_migrations() in migrations.py

    Examples:
        # Create a new collection with indexes
        async def up(self, db_client: MongoDBClient) -> None:
            if not db_client.db:
                raise RuntimeError("Database not connected")

            db = db_client.db
            await db.my_collection.create_index("field_name", unique=True)

        # Add a field to existing documents
        async def up(self, db_client: MongoDBClient) -> None:
            if not db_client.db:
                raise RuntimeError("Database not connected")

            db = db_client.db
            result = await db.collection.update_many(
                {{"new_field": {{"$exists": False}}}},
                {{"$set": {{"new_field": "default_value"}}}}
            )
            print(f"  Updated {{result.modified_count}} documents")
    """

    def __init__(self) -> None:
        super().__init__(
            "{version_name}",
            "{description}"
        )

    async def up(self, db_client: MongoDBClient) -> None:
        """Apply migration."""
        if not db_client.db:
            raise RuntimeError("Database not connected")

        db = db_client.db

        # TODO: Implement migration logic here
        # Example:
        # await db.collection.create_index("field_name")
        # result = await db.collection.update_many(
        #     {{"field": {{"$exists": False}}}},
        #     {{"$set": {{"field": "value"}}}}
        # )
        # print(f"  Updated {{result.modified_count}} documents")

        pass

    async def down(self, db_client: MongoDBClient) -> None:
        """Rollback migration."""
        if not db_client.db:
            raise RuntimeError("Database not connected")

        db = db_client.db

        # TODO: Implement rollback logic here
        # Example:
        # await db.collection.update_many(
        #     {{}},
        #     {{"$unset": {{"field": ""}}}}
        # )

        pass
'''

    @staticmethod
    def create_migration_file(
        migrations_dir: Path,
        name: str,
        description: str = ""
    ) -> Path:
        """
        Create a new migration file.

        Args:
            migrations_dir: Directory to create migration in
            name: Migration name
            description: Optional description

        Returns:
            Path to created migration file

        Raises:
            ValueError: If name is invalid
            FileExistsError: If migration file already exists
        """
        if not MigrationTemplate.validate_name(name):
            raise ValueError(
                f"Invalid migration name: '{name}'. "
                "Name must start with a letter and contain only lowercase letters, "
                "numbers, and underscores."
            )

        # Ensure migrations directory exists
        migrations_dir.mkdir(parents=True, exist_ok=True)

        # Get next version
        version = MigrationTemplate.get_next_version(migrations_dir)

        # Generate filename
        filename = MigrationTemplate.generate_filename(version, name)
        filepath = migrations_dir / filename

        # Check if file already exists
        if filepath.exists():
            raise FileExistsError(f"Migration file already exists: {filepath}")

        # Generate content
        content = MigrationTemplate.generate_content(version, name, description)

        # Write file
        filepath.write_text(content)

        return filepath
